<template>
    <ChildBaseLayout page-title="多巴案例">
        <template v-slot:actions-end>
            <ion-button id="open-modal">
                <ion-icon slot="icon-only" :icon="add"></ion-icon>
            </ion-button>
        </template>
        <ion-modal ref="modal" trigger="open-modal" :initial-breakpoint="1" :breakpoints="[0, 1]">
            <div class="block">
                <div>
                    <ion-input label="案例名称" v-model="dopaNameInput" label-placement="stacked" placeholder="请输入名称"
                        :counter="true" :maxlength="20" required></ion-input>
                </div>
                <div class="action-btn">
                    <ion-button expand="block" color="danger" @click="close()">
                        取消
                    </ion-button>
                    <ion-button expand="block" color="success" @click="confirm()">
                        确认
                    </ion-button>
                </div>
            </div>
        </ion-modal>
        <ion-list lines="full" class="dopa-case-list" contenteditable="false">
            <div v-for="dopamine in SqliteStore.dopamines" class="list-item">
                <ion-label :id="'dopaLaber' + dopamine.id" contenteditable="true" class="laber"
                    @blur="updateDopaName($event, dopamine)"> {{ dopamine.name
                    }}</ion-label>

                <ion-icon aria-hidden="true" contenteditable="false" @blur="" size="small"
                    @click="showDeleteDopaCaseAlert(dopamine.id)" icon="assets/trash.svg" />
            </div>

        </ion-list>
        <ion-alert :is-open="isOpen" header="错误提醒" :buttons="alertButtons" message="不能删除当前使用的案例"
            @didDismiss="setOpen(false)">
        </ion-alert>
        <ion-alert :is-open="isDeleteAlertOpen" header="提醒!" message="确定要删除吗？" :buttons="DeletealertButtons">
        </ion-alert>
    </ChildBaseLayout>
</template>
<script lang="ts" setup>
import { IonAlert, IonList, IonItem, IonLabel, IonModal, IonButton, IonInput, IonIcon, toastController } from '@ionic/vue';
import { add } from "ionicons/icons";
import { ref, defineProps } from 'vue'

import ChildBaseLayout from '@/components/app/ChildBaseLayout.vue';
const props = defineProps(['pageDefaultBackLink'])

import { useMySqliteStore } from '@/stores/sqlite'
import { Dopamine } from '@/models/Dopamine';
import { Toast } from '@capacitor/toast';
const SqliteStore = useMySqliteStore()

const dopaNameInput = ref('')
const modal = ref();

const convertToTwoDigit = (number: number) => {
    return number < 10 ? '0' + number.toString() : number.toString();
}
const dateToString = (date: Date) => {
    return `${date.getFullYear()}-${convertToTwoDigit(date.getMonth() + 1)}-${convertToTwoDigit(date.getDate())}`
}

const close = () => {
    dopaNameInput.value = ''
    modal.value.$el.dismiss();
}
const confirm = () => {
    if (dopaNameInput.value != '') {
        const newDapamine = {
            id: Date.now(), // do not care about the id value (generated by sqlite)
            name: dopaNameInput.value,
            startDate: dateToString(new Date()),
            recordBestThinkDay: 0,
            recordBestDoDay: 0,
            allDoDayCount: 0,
            allThinkDayCount: 0,
            daysCount: 0,
            dopaHistorys: []
        };
        dopaNameInput.value = ''
        SqliteStore.handleAddDopamine(newDapamine)
        modal.value.$el.dismiss();
    }

}
const isOpen = ref(false)
const alertButtons = ['确认'];
const setOpen = (state: boolean) => {
    isOpen.value = state;
};


let localDopaId: number;
const showDeleteDopaCaseAlert = (dopaId: number) => {
    let dopaCaseActiveId = SqliteStore.selectedDopaCaseSegment.replace("d", '')
    if (dopaId == dopaCaseActiveId) {
        console.log('can not delete select dopaCase')
        isOpen.value = true
    } else {
        isDeleteAlertOpen.value = true
        //console.log('open delete alert')
        localDopaId = dopaId
        //SqliteStore.handleDeleteDopamine(dopaId)
    }

}


const isDeleteAlertOpen = ref(false)
const DeletealertButtons = [
    {
        text: '取消',
        role: 'cancel',
        handler: () => {
            //console.log('Alert canceled');
            isDeleteAlertOpen.value = false
        },
    },
    {
        text: '确认',
        role: 'confirm',
        handler: () => {
            //console.log('Alert confirmed');
            isDeleteAlertOpen.value = false
            SqliteStore.handleDeleteDopamine(localDopaId)
        },
    },
];



const updateDopaName = async (event: Event, dopamine: Dopamine) => {
    event.preventDefault()
    let dopaLaber = document.getElementById('dopaLaber' + dopamine.id) as HTMLInputElement
    //console.log('Update', event, dopaLaber.textContent)

    if (dopamine.name != dopaLaber.textContent && dopaLaber.textContent!.length <= 20) {
        dopamine.name = dopaLaber.textContent!
        SqliteStore.handleUpdateDopamine(dopamine)

        const toast = await toastController.create({
            message: '名称更新!',
            duration: 500,
            position: 'top',
        });
        await toast.present();
    } else if (dopaLaber.textContent!.length > 20) {
        const toast = await toastController.create({
            message: '名称更新错误，名称长度不能超20!',
            duration: 500,
            position: 'top',
        });
        await toast.present();
    }



}


</script>
<style scoped lang="less">
.block {
    width: 100%;
    height: 300px;
    display: flex;
    flex-direction: column;
    justify-content: space-evenly;
    padding: 0 20px;
}

ion-modal {
    --height: auto;
}

.action-btn {
    display: grid;
    grid-template-columns: auto auto;
}

.dopa-case-list {
    .list-item {
        display: grid;
        grid-template-columns: auto 50px;
        min-height: 50px;
        align-items: center;
        border-bottom: 1px solid var(--ion-color-light-shade);

        .laber {
            margin-left: 20px;
        }
    }

    ion-icon {
        margin-left: 10px;
    }
}
</style>